const ass_head = `[Script Info]
; Script generated by KARASS
Title: Default KARASS file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 940

[Aegisub Project Garbage]
Last Style Storage: Default
Video File: ?dummy:23.976000:40000:640:480:47:163:254:
Video AR Value: 1.333333
Video Zoom Percent: 0.500000
Scroll Position: 0
Active Line: 1
Video Position: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,RocknRoll One,98,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3.91667,3.91667,2,353,353,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text`;

// Dialogue: 0,0:02:18.90,0:02:22.50,Default,,0,0,0,karaoke,The day will come, the sun will rise
function assFmtTimeMs(ms) {
    return new Date(ms).toISOString().slice(11, -1);
}

function assFmtLineRaw(lineObj) {
    return "Dialogue: 0," + assFmtTimeMs(lineObj.start * 1000) + "," + assFmtTimeMs(lineObj.end * 1000) + ",Default,,0,0,0,karaoke," + lineObj.raw;
}

function genAssFile(name) {
    let assContent = ass_head + "\n" + lines.map(x => assFmtLineRaw(x)).join('\n');
    download(assContent, "text/plain", name + ".ass");
}